# Generated by Django 6.0.5 on 2026-06-06 14:25

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WilayahKabupaten',
            fields=[
                ('nama', models.CharField(default='', max_length=200)),
                ('kode_kabupaten', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('koordinat', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Pangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, default='', max_length=100)),
                ('harga_acuan', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('satuan', models.CharField(blank=True, max_length=255, null=True)),
                ('master_id', models.CharField(max_length=20)),
                ('sumber_id', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sumber_id', 'master_id'), name='unique_master_per_sumber'), models.UniqueConstraint(fields=('sumber_id', 'slug'), name='unique_slug_per_sumber'), models.UniqueConstraint(fields=('sumber_id', 'nama'), name='unique_nama_per_sumber')],
            },
        ),
        migrations.CreateModel(
            name='WilayahKecamatan',
            fields=[
                ('nama', models.CharField(default='', max_length=200)),
                ('kode_kecamatan', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('koordinat', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('kabupaten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistem.wilayahkabupaten')),
            ],
            options={
                'unique_together': {('kabupaten', 'kode_kecamatan')},
            },
        ),
        migrations.CreateModel(
            name='WilayahPasar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.IntegerField(unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('tipe_pasar', models.PositiveSmallIntegerField(default=3)),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem.wilayahkabupaten')),
            ],
        ),
        migrations.CreateModel(
            name='PrediksiArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_tipe', models.CharField(max_length=12)),
                ('artifact_path', models.CharField(max_length=255)),
                ('trained_at', models.DateField()),
                ('train_periods', models.PositiveIntegerField()),
                ('last_snapshot_period_end', models.DateField()),
                ('eval_mae_h1', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('eval_mae_h4', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem.pangan')),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem.wilayahkabupaten')),
            ],
            options={
                'unique_together': {('pangan', 'kabupaten', 'periode_tipe')},
            },
        ),
        migrations.CreateModel(
            name='HargaPangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_update', models.DateField()),
                ('harga_sekarang', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('harga_terakhir', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=12, null=True)),
                ('tanggal_terakhir', models.DateField(blank=True, default=None, null=True)),
                ('is_up', models.BooleanField(blank=True, null=True)),
                ('pangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem.pangan')),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistem.wilayahkabupaten')),
            ],
            options={
                'indexes': [models.Index(fields=['pangan', 'kabupaten', 'tanggal_update'], name='idx_hargapangan_stream'), models.Index(fields=['pangan', 'tanggal_update'], name='idx_hargapangan_pangan_date')],
                'constraints': [models.UniqueConstraint(fields=('pangan', 'tanggal_update', 'kabupaten'), name='unique_pangan_harian_kabupaten', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='WilayahDesa',
            fields=[
                ('nama', models.CharField(default='', max_length=200)),
                ('kode_desa', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('koordinat', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('kabupaten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relasi_wil_kabupaten', to='sistem.wilayahkabupaten')),
                ('kecamatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relasi_wil_kecamatan', to='sistem.wilayahkecamatan')),
            ],
            options={
                'unique_together': {('kabupaten', 'kecamatan', 'kode_desa')},
            },
        ),
        migrations.CreateModel(
            name='HargaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_tipe', models.CharField(max_length=12)),
                ('periode_tahun', models.PositiveSmallIntegerField()),
                ('periode_nomor', models.PositiveSmallIntegerField()),
                ('periode_start', models.DateField()),
                ('periode_end', models.DateField()),
                ('harga_lkv', models.DecimalField(decimal_places=3, max_digits=12)),
                ('tanggal_lkv', models.DateField()),
                ('is_locf', models.BooleanField(default=False)),
                ('harga_lkv_prev', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('harga_delta', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('is_up', models.BooleanField(blank=True, null=True)),
                ('harga_lag1', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('harga_lag2', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('harga_lag3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pangan', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='sistem.pangan')),
                ('kabupaten', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='sistem.wilayahkabupaten')),
                ('pasar', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistem.wilayahpasar')),
            ],
            options={
                'indexes': [models.Index(fields=['pangan', 'kabupaten', 'periode_tipe', 'periode_tahun', 'periode_nomor'], name='idx_snapshot_stream'), models.Index(fields=['kabupaten', 'periode_tipe', 'periode_tahun', 'periode_nomor'], name='idx_snapshot_kab_period')],
                'constraints': [models.UniqueConstraint(fields=('pangan', 'kabupaten', 'pasar', 'periode_tipe', 'periode_tahun', 'periode_nomor'), name='unique_snapshot_periode', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='HargaPanganWholesaleMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_update', models.DateField()),
                ('harga', models.DecimalField(decimal_places=3, max_digits=12)),
                ('pangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem.pangan')),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistem.wilayahkabupaten')),
                ('pasar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem.wilayahpasar')),
            ],
            options={
                'indexes': [models.Index(fields=['pangan', 'kabupaten', 'tanggal_update'], name='idx_wholesale_market_stream')],
                'constraints': [models.UniqueConstraint(fields=('pangan', 'pasar', 'tanggal_update'), name='unique_wholesale_market_daily')],
            },
        ),
    ]
